/* EdgeKWS v2 — lightweight monitor data layer. */
const systemData={mode:"demo",deviceId:"esp32s3_001",cpuPercent:6.2,ramUsedKb:147,ramLimitKb:256,voltage:3.30,currentMa:6.0,powerMw:19.8,inferenceMs:4.7,wakeLatencyMs:85,confidence:12.4,threshold:85,state:"LISTENING",detectionsToday:18,falseActivations:0,lastDetection:"--:--:--",powerHistory:[19.4,20.1,19.8,18.9,20.6,21.2,19.8],timeLabels:["T-6","T-5","T-4","T-3","T-2","T-1","NOW"]};
const $=id=>document.getElementById(id),fmt=(v,d=1)=>Number(v).toFixed(d);let powerChart,demoEventTimer;
function sourceLabel(){return systemData.mode==="firebase"?"FIREBASE LIVE":"SIMULATED"}
function applyData(incoming={}){Object.assign(systemData,incoming);const ramPct=systemData.ramLimitKb?(systemData.ramUsedKb/systemData.ramLimitKb)*100:0;const listening=String(systemData.state).toUpperCase()!=="WAKE DETECTED";
$("deviceId").textContent=systemData.deviceId;$("sideLink").textContent=sourceLabel();$("sideSource").textContent=sourceLabel();$("linkStatus").textContent=systemData.mode==="firebase"?"LIVE":"DEMO";$("footerMode").textContent=systemData.mode==="firebase"?"FIREBASE LIVE":"DEMO / SIMULATED";$("connectionBadge").textContent=systemData.mode==="firebase"?"LIVE":"DEMO";$("frontendMode").textContent=systemData.mode==="firebase"?"FIREBASE LIVE":"DEMO / SIMULATED";$("firebasePath").textContent=`devices/${systemData.deviceId}/live`;$("telemetryUpdate").textContent=systemData.mode==="firebase"?new Date().toLocaleTimeString([], {hour12:false}):"Not connected";
$("cpu").textContent=fmt(systemData.cpuPercent)+"%";$("cpuBar").style.width=Math.min(Math.max(systemData.cpuPercent*10,0),100)+"%";$("cpuStatus").textContent=systemData.cpuPercent<10?"TARGET STATUS // PASS":"TARGET STATUS // ABOVE LIMIT";$("ram").textContent=fmt(systemData.ramUsedKb,0);$("ramPercent").textContent=fmt(ramPct)+"%";$("ramBar").style.width=Math.min(Math.max(ramPct,0),100)+"%";$("power").textContent=fmt(systemData.powerMw);$("powerFormula").textContent=fmt(systemData.powerMw);$("voltage").textContent=fmt(systemData.voltage,2)+" V";$("current").textContent=fmt(systemData.currentMa)+" mA";$("powerFormulaText").textContent=`${fmt(systemData.voltage,2)} V × ${fmt(systemData.currentMa)} mA`;$("inference").textContent=fmt(systemData.inferenceMs);$("latency").textContent=fmt(systemData.inferenceMs);$("confidence").textContent=fmt(systemData.confidence)+"%";$("confidenceBar").style.width=Math.min(Math.max(systemData.confidence,0),100)+"%";$("threshold").textContent=fmt(systemData.threshold,0)+"%";$("thresholdMark").style.left=Math.min(Math.max(systemData.threshold,0),100)+"%";$("detections").textContent=systemData.detectionsToday;$("falseActivations").textContent=systemData.falseActivations;$("lastDetection").textContent=systemData.lastDetection||"--:--:--";
$("kwsState").textContent=listening?"LISTENING":"WAKE DETECTED";$("kwsBadge").textContent=listening?"LISTENING":"WAKE DETECTED";$("modePill").textContent=listening?"IDLE LISTENING":"WAKE EVENT ACTIVE";$("signalState").textContent=listening?"DECISION":"WAKE EVENT";$("eventSignal").textContent=listening?"ARMED":"TRIGGERED";$("eventText").textContent=listening?"LISTENING FOR WAKE PHRASE":"KEYWORD DETECTED — START ASR";$("eventSubtext").textContent=listening?"No keyword event detected":`Confidence ${fmt(systemData.confidence)}%`;$("eventIndicator").classList.toggle("detected",!listening);$("reactor").classList.toggle("detected",!listening);
$("demoBanner").innerHTML=systemData.mode==="firebase"?"● FIREBASE LIVE TELEMETRY <span>— values below are received from the configured Firebase Realtime Database path</span>":"◆ DEMO / SIMULATED DATA <span>— values become live when Firebase receives ESP32 telemetry</span>";
const p=Array.isArray(systemData.powerHistory)?systemData.powerHistory:[];if(p.length){const a=p.reduce((x,y)=>x+y,0)/p.length;$("powerAvg").textContent=fmt(a);$("powerRange").textContent=`${fmt(Math.min(...p))}–${fmt(Math.max(...p))}`}updatePowerChart();}
function updatePowerChart(){if(!powerChart)return;powerChart.data.labels=systemData.timeLabels;powerChart.data.datasets[0].data=systemData.powerHistory;powerChart.update("none")}
function initPowerChart(){const c=$("powerChart");if(!c||!window.Chart)return;powerChart=new Chart(c.getContext("2d"),{type:"line",data:{labels:systemData.timeLabels,datasets:[{data:systemData.powerHistory,borderColor:"#55f2a5",backgroundColor:"rgba(85,242,165,.045)",borderWidth:2,pointRadius:2,pointHoverRadius:4,fill:true,tension:.3}]},options:{responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{display:false},tooltip:{mode:"index",intersect:false}},scales:{x:{grid:{color:"rgba(57,220,255,.05)"},ticks:{color:"#4e6a75",font:{family:"JetBrains Mono",size:8}}},y:{grid:{color:"rgba(57,220,255,.06)"},ticks:{color:"#4e6a75",font:{family:"JetBrains Mono",size:8}}}}}})}
function tickDemo(){if(systemData.mode!=="demo")return;systemData.powerMw=Math.max(18.7,Math.min(21.4,systemData.powerMw+(Math.random()-.5)*.45));systemData.currentMa=systemData.powerMw/systemData.voltage;systemData.cpuPercent=Math.max(4.8,Math.min(7.5,systemData.cpuPercent+(Math.random()-.5)*.5));systemData.powerHistory=[...systemData.powerHistory.slice(1),Number(systemData.powerMw.toFixed(1))];applyData()}
function demoWakeEvent(){if(systemData.mode!=="demo")return;if(Math.random()<.14){systemData.state="WAKE DETECTED";systemData.confidence=91+Math.random()*7;systemData.detectionsToday+=1;systemData.lastDetection=new Date().toLocaleTimeString([], {hour12:false});applyData();clearTimeout(demoEventTimer);demoEventTimer=setTimeout(()=>{systemData.state="LISTENING";systemData.confidence=8+Math.random()*12;applyData()},2200)}}
function updateClock(){const n=new Date();$("clock").textContent=n.toLocaleTimeString([], {hour12:false});$("date").textContent=n.toLocaleDateString([], {month:"short",day:"2-digit",year:"numeric"})}
function initNavigation(){document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("page-"+b.dataset.page).classList.add("active");$("sidebar").classList.remove("open")}));$("mobileMenu").addEventListener("click",()=>$("sidebar").classList.toggle("open"))}
window.addEventListener("load",async()=>{initNavigation();updateClock();setInterval(updateClock,1000);initPowerChart();applyData();setInterval(tickDemo,2500);setInterval(demoWakeEvent,5000);if(window.EdgeKWSFirebase){try{await window.EdgeKWSFirebase.connect(systemData.deviceId,data=>{if(!data)return;systemData.mode="firebase";applyData(data)})}catch(e){console.info("Firebase unavailable; demo mode remains active.",e)}}});
